# Generated by Django 4.2.4 on 2023-12-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
