# Generated by Django 4.2.4 on 2023-12-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DietaryOptions',
            new_name='DietaryOption',
        ),
        migrations.RenameModel(
            old_name='MenuOptions',
            new_name='MenuOption',
        ),
        migrations.RenameModel(
            old_name='VenuePhotos',
            new_name='VenuePhoto',
        ),
    ]
