# Generated by Django 4.2.4 on 2023-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_dietaryoptions_dietaryoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasEggsOptions',
            field=models.BooleanField(default=False, help_text='Can you choose how to cook the eggs?'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasGravyOptions',
            field=models.BooleanField(default=False, help_text='Can you add gravy?'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasRemovableOptions',
            field=models.BooleanField(default=False, help_text='Can you remove ingredients? Eg, no onion on burger'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasSauceOptions',
            field=models.BooleanField(default=False, help_text='Can you choose the sauce? Eg, dijon or tomato on burgers'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasSidesOptions',
            field=models.BooleanField(default=False, help_text='Does dish come with a choice of sides? Eg, salad, add chicken, spaghetti'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='hasSizeOptions',
            field=models.BooleanField(default=False, help_text='Does dish come in different sizes?'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='inStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
