# Generated by Django 4.2.4 on 2023-12-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
