# Generated by Django 4.2.4 on 2023-12-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_drinkphoto_eventphoto_events_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='added_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.addedoption'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='gravy_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.gravyoption'),
        ),
    ]
