# Generated by Django 4.2.4 on 2023-12-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenuitem',
            name='hasEggsOptions',
        ),
        migrations.RemoveField(
            model_name='foodmenuitem',
            name='hasGravyOptions',
        ),
        migrations.RemoveField(
            model_name='foodmenuitem',
            name='hasRemovableOptions',
        ),
        migrations.RemoveField(
            model_name='foodmenuitem',
            name='hasSauceOptions',
        ),
        migrations.RemoveField(
            model_name='foodmenuitem',
            name='hasSizeOptions',
        ),
    ]
