# Generated by Django 4.2.4 on 2023-12-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_foodmenuitem_haseggsoptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dish', models.ManyToManyField(to='main_app.foodmenuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Sides',
        ),
    ]
