# Generated by Django 4.2.4 on 2023-12-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_lineitem_added_option_lineitem_gravy_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Pick_up', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='None', help_text='Enter a name for the order', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_deliver',
            field=models.CharField(choices=[('P', 'Pick up'), ('D', 'Delivery')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
