# Generated by Django 4.2.4 on 2023-12-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_foodmenuitem_hassidesoptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CookOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GravyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RemoveOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SauceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='sideoption',
            name='price',
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='side_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.sideoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='added_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.addedoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='cook_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.cookoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='gravy_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.gravyoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='remove_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.removeoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='sauce_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.sauceoption'),
        ),
        migrations.AddField(
            model_name='foodmenuitem',
            name='size_option',
            field=models.ManyToManyField(help_text='Select all that apply', to='main_app.sizeoption'),
        ),
    ]
