# Generated by Django 4.2.4 on 2023-12-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_addedoption_cookoption_gravyoption_removeoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenuitem',
            name='added_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.addedoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='cook_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.cookoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='gravy_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.gravyoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='remove_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.removeoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='sauce_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.sauceoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='side_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.sideoption'),
        ),
        migrations.AlterField(
            model_name='foodmenuitem',
            name='size_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.sizeoption'),
        ),
    ]
