# Generated by Django 4.2.4 on 2023-12-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_venuephoto_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
        ),
    ]
