# Generated by Django 4.2.4 on 2023-12-20 06:21

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_eventphoto_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
