# Generated by Django 4.2.4 on 2023-12-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_order_address_alter_order_phone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marketing',
            field=models.BooleanField(default=False),
        ),
    ]
