# Generated by Django 4.2.4 on 2023-12-20 23:29

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
