# Generated by Django 4.2.4 on 2023-12-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order_iscomplete_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='order',
            name='isInProgress',
            field=models.BooleanField(default=True),
        ),
    ]
