# Generated by Django 4.2.4 on 2023-12-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_order_iscomplete_order_isinprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='item',
        ),
    ]
