# Generated by Django 4.2.4 on 2023-12-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_lineitem_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftDrinkOption',
            new_name='SoftDrinkSizeOption',
        ),
        migrations.RenameField(
            model_name='drinkmenuitem',
            old_name='soft_drink_option',
            new_name='soft_drink_size_option',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
