# Generated by Django 4.2.4 on 2023-12-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_softdrinkoption_softdrinksizeoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='coffee_size_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.coffeesizeoption'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='coffee_strength_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.coffeestrengthoption'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='hot_chocolate_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.hotchocolateoption'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='milk_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.milkoption'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='soft_drink_size_option',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='main_app.softdrinksizeoption'),
        ),
    ]
